# Model settings
transition: 'marginal'                          # uniform, marginal, argmax, absorbfirst, absorbing
model: 'graph_tf'
n_layers: 5

extra_features: 'rrwp'        # 'all', 'cycles', 'eigenvalues', 'rrwp', 'rrwp_comp' or null
rrwp_steps: 12

# Do not set hidden_mlp_E, dim_ffE too high, computing large tensors on the edges is costly
hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}

# The dimensions should satisfy dx % n_head == 0
hidden_dims : {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}

# training weight for edges, y, and nodes
lambda_train: [5, 0]              # X=1, E = lambda[0], y = lambda[1]

# --------- Parameters that support override ---------
use_ot: True
use_improved_ot: True

ot_reg: 0.30344418198213097
num_steps: 30
temp: 1.0915451233180051
alpha: 0.7180003054048231
beta: 1.2971087524968663